### ISSUE TITLE
Duration on teams Alert shows wrong value

### ISSUE THREAD

**Issue by asiva406** [ctrf-io/microsoft-teams-test-reporter#1]
Duration shows wrongly in the teams alert for cypress. Actual test duration is 16 sec but alert shows 10 mins. Please check 
![image](https://github.com/user-attachments/assets/adfe8c7f-7b0c-4f07-970a-78cfeb6e6ad4)

![image](https://github.com/user-attachments/assets/83f67d66-d6ea-4483-b9a2-25d5f588e9de)

**Comment by Ma11hewThomas** [comment]
Thanks, published version 0.0.5
